### ISSUE TITLE
The app crashes when writing the title "Title (mandatory)"

### ISSUE THREAD

**Issue by Xapitonov** [Swatian/nexnotes#6] opened 2024-08-08 06:55 UTC
android.view.InflateException: Binary XML file line #60: Binary XML file line #60: Error inflating class TextView
Caused by: android.view.InflateException: Binary XML file line #60: Error inflating class TextView
Caused by: android.content.res.Resources$NotFoundException: Drawable com.swatian.nexnotes:color/biometric_error_color with resource ID #0x7f060021
Caused by: android.content.res.Resources$NotFoundException: File res/color-v26/biometric_error_color.xml from drawable resource ID #0x7f060021
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:854)
	at android.content.res.ResourcesImpl.loadDrawable(ResourcesImpl.java:634)
	at android.content.res.MiuiResourcesImpl.loadDrawable(MiuiResourcesImpl.java:327)
	at android.content.res.Resources.loadDrawable(Resources.java:911)
	at android.content.res.TypedArray.getDrawableForDensity(TypedArray.java:957)
	at android.content.res.TypedArray.getDrawable(TypedArray.java:932)
	at android.view.View.<init>(View.java:5019)
	at android.widget.TextView.<init>(TextView.java:875)
	at android.widget.TextView.<init>(TextView.java:869)
	at androidx.appcompat.widget.AppCompatTextView.<init>(AppCompatTextView.java:115)
	at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:92)
	at com.google.android.material.textview.MaterialTextView.<init>(MaterialTextView.java:87)
	at com.google.android.material.theme.MaterialComponentsViewInflater.createTextView(MaterialComponentsViewInflater.java:61)
	at androidx.appcompat.app.AppCompatViewInflater.createView(AppCompatViewInflater.java:148)
	at androidx.appcompat.app.AppCompatDelegateImpl.createView(AppCompatDelegateImpl.java:1654)
	at androidx.appcompat.app.AppCompatDelegateImpl.onCreateView(AppCompatDelegateImpl.java:1705)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:776)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:734)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:867)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.rInflate(LayoutInflater.java:870)
	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:828)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:519)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
	at com.swatian.nexnotes.adapters.NotesAdapter.onCreateViewHolder(NotesAdapter.java:132)
	at com.swatian.nexnotes.adapters.NotesAdapter.onCreateViewHolder(NotesAdapter.java:35)
	at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:7078)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6235)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LayoutState.next(LayoutState.java:98)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1607)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:683)
	at androidx.recyclerview.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:605)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at androidx.swiperefreshlayout.widget.SwipeRefreshLayout.onLayout(SwipeRefreshLayout.java:689)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1213)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:899)
	at com.google.android.material.appbar.ViewOffsetBehavior.layoutChild(ViewOffsetBehavior.java:66)
	at com.google.android.material.appbar.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:153)
	at com.google.android.material.appbar.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:43)
	at com.google.android.material.appbar.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:2365)
	at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:918)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1873)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
	at com.android.internal.policy.DecorView.onLayout(DecorView.java:757)
	at android.view.View.layout(View.java:20699)
	at android.view.ViewGroup.layout(ViewGroup.java:6198)
	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2835)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2362)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1500)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7342)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1037)
	at android.view.Choreographer.doCallbacks(Choreographer.java:833)
	at android.view.Choreographer.doFrame(Choreographer.java:768)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1023)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6810)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
Caused by: org.xmlpull.v1.XmlPullParserException: Binary XML file line #21: <item> tag requires a 'drawable' attribute or child tag defining a drawable
	at android.graphics.drawable.StateListDrawable.inflateChildElements(StateListDrawable.java:190)
	at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:122)
	at android.graphics.drawable.DrawableInflater.inflateFromXmlForDensity(DrawableInflater.java:142)
	at android.graphics.drawable.Drawable.createFromXmlInnerForDensity(Drawable.java:1332)
	at android.graphics.drawable.Drawable.createFromXmlForDensity(Drawable.java:1291)
	at android.content.res.ResourcesImpl.createFromXmlForDensity(ResourcesImpl.java:1506)
	at android.content.res.ResourcesImpl.loadDrawableForCookie(ResourcesImpl.java:838)
	... 107 more

**Comment by mmarif4u** [comment] 2024-08-08 15:19
What is your Android version and device?

**Comment by Xapitonov** [comment] 2024-08-08 15:58
чт, 8 авг. 2024 г., 19:19 M M Arif ***@***.***>:

**Comment by Xapitonov** [comment] 2024-08-08 16:07
чт, 8 авг. 2024 г., 19:57 Сергей Харитонов ***@***.***>:

**Comment by mmarif4u** [comment] 2024-08-09 11:24
I don't see the information requested.

It would be helpful if you can provide more info like how to reproduce it?

**Comment by mmarif4u** [comment] 2024-09-09 17:47
Closing this as the issue is not reproducible and may have occurred only during your tests on your system.

**Closed by mmarif4u** 2024-09-09 17:47 UTC
Labels: needs-feedback
